### PR TITLE
v6.0.1

### PR DESCRIPTION
**Pull request by bugsounet**
Testing @KristjanESPERANTO Recommendations

Fix:
 * typo in fr.json (MMM-GoogleAssisztant -> MMM-GoogleAssistant)
 * typo in website/gateway/tools.html -> MagicMirror²
 * review force 32bits kernel with 32bits userspace (bookworm)

Update: 
  * add more time before init smarthome (30 sec) and add log when initialized
  * add 3rd party module list link in MMM-GoogleAssistant website (Thx @KristjanESPERANTO)
  * add MM² GPU accelerated rendering information on website, screen and TelegramBot
  * add GA Version on sysinfo (screen and telegrambot)

Update Dependencies:
  * open
  * google-auth-library

### CODE REVIEW

**Comment by KristjanESPERANTO** [comment]
Nice! I think you'r referring to [these recommendations](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md#MMM-GoogleAssistant-by-bugsounet). Feel free to give me feedback. If there's anything you don't like or if you have any ideas for new tests. Some things are certainly not perfect 🙂

**Comment by bugsounet** [comment]
@KristjanESPERANTO:  

I Clone it for testing result but maybe can we test only a single repo instead of all? (in my case this repo)
Right, I assume that I have change git target to dev branch for testing :)

image

fontawesome and jquery: I can't do better

what bothers me is that my EXTs are not tested, I don't have much idea other than putting them in the 3rd wiki :/

**Comment by KristjanESPERANTO** [comment]
> test only a single repo

A that would be a good feature. I'll put that on my to-do list. Maybe I'll manage it in the next few days.

> fontawesome and jquery: I can't do better

Okay, that doesn't make much sense with 3rd party stuff. I'll have a closer look and see if I have any ideas.

Just a spontaneous idea: If it would be possible to include jquery and fontawesome as dependency? Then it would not be directly in the repository.

> what bothers me is that my EXTs are not tested, I don't have much idea other than putting them in the 3rd wiki :/

It would be great if you included your other modules there. Then I would also test them and they would be listed on the [resulting web page](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/).

**Comment by bugsounet** [comment]
MMM-GoogleAssistant [EXTs](https://github.com/MagicMirrorOrg/MagicMirror/wiki/3rd-party-modules#extended-plugins-for-mmm-googleassistant-by-bugsounet) are added

I make a new section because they can't work without MMM-GoogleAssistant

**Comment by KristjanESPERANTO** [comment]
Okay, what do think about this: [Special script: create_own_module_list.js](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules#special-script-create_own_module_listjs)?

**Comment by bugsounet** [comment]
> Okay, what do think about this: [Special script: create_own_module_list.js](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules#special-script-create_own_module_listjs)?

by testing `npm run ownList`:

It really that I need ;)
but `branch` in `ownModuleList.json` don't works (using your default test file)

```sh
bugsounet@Kubuntu:~/MagicMirror-3rd-Party-Modules/modules/MMM-GoogleAssistant-----bugsounet$ git branch
* prod
```

**Comment by bugsounet** [comment]
I think to do this With `MMM-GoogleAssistant` Website

make an Iframe to your [result](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) page for integrate it

Why an iframe ? otherwise I will lose my navbar :p

**Comment by KristjanESPERANTO** [comment]
> but branch in ownModuleList.json don't works (using your default test file)

Thats odd.

```bash
kristjan@debian:~/Development/MagicMirror-3rd-Party-Modules$ npm run ownList

> magicmirror-3rd-party-modules@0.1.0 ownList
> rm -r modules & node create_own_module_list.js && python3 get_modules.py && node expand_module_list_with_repo_data.js && python3 check_modules.py


+++      1: MMM-Canteen by KristjanESPERANTO - https://github.com/KristjanESPERANTO/MMM-Canteen
- I - path doesn't exists: run `git clone`
Cloning into 'modules_temp/MMM-Canteen-----KristjanESPERANTO'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 22 (delta 0), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (22/22), 125.81 KiB | 1.57 MiB/s, done.

+++      2: MMM-GoogleAssistant by bugsounet - https://github.com/bugsounet/MMM-GoogleAssistant/
- I - run `git clone --branch {module['branch']}` 
Cloning into 'modules_temp/MMM-GoogleAssistant-----bugsounet'...
remote: Enumerating objects: 321, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 321 (delta 58), reused 214 (delta 30), pack-reused 0
Receiving objects: 100% (321/321), 4.87 MiB | 5.26 MiB/s, done.
Resolving deltas: 100% (58/58), done.

+++      3: MMM-ISS-Live by KristjanESPERANTO - https://github.com/KristjanESPERANTO/MMM-ISS-Live
- I - run `git clone --branch {module['branch']}` 
Cloning into 'modules_temp/MMM-ISS-Live-----KristjanESPERANTO'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 14 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 310.67 KiB | 2.46 MiB/s, done.

- I - Modules found and downloaded: 3

+++ MMM-Canteen by KristjanESPERANTO
+++ MMM-GoogleAssistant by bugsounet
+++ MMM-ISS-Live by KristjanESPERANTO
3 modules analyzed. For results see file result.md.           
kristjan@debian:~/Development/MagicMirror-3rd-Party-Modules$ cd modules/MMM-GoogleAssistant-----bugsounet/
kristjan@debian:~/Development/MagicMirror-3rd-Party-Modules/modules/MMM-GoogleAssistant-----bugsounet$ git branch
* dev
```

Except for the faulty log output, it works for me 🤔. Can you manually delete the modules folder and then try again?

**Comment by bugsounet** [comment]
you have right ! it's works AFTER delete all modules ;)

**Comment by KristjanESPERANTO** [comment]
> Can I do it?

Sure. I would be delighted :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
> you have right ! it's works AFTER delete all modules ;)

Nice. But of course it should work without that manual deletion....

**Comment by bugsounet** [comment]
ah... we have something in common... we don't like creating problems ;)

**Comment by KristjanESPERANTO** [comment]
Yeah! :slightly_smiling_face: 

But I think I just fixed it with the last commit...

**Comment by bugsounet** [comment]
@KristjanESPERANTO

This is "the first" approach 

image

**Comment by KristjanESPERANTO** [comment]
> This is "the first" approach

Looks good! Maybe the whole thing will eventually develop into an app store where the user only has to click an install button 😀

**Comment by bugsounet** [comment]
Sure,

I have do this with website of MMM-GoogleAssistant for EXTs:
 * install
 * delete
 * configuration with template
 * modify configuration (if needed)
 * merge template with current config (if needed)
 * create new config.js with new EXT
 * edit MagicMirror² config
 * backup of the old config
 * call backup is needed
 * ...

see [there](https://wiki.bugsounet.fr/MMM-GoogleAssistant/website)

**Comment by KristjanESPERANTO** [comment]
Wow, that's very impressive! I have to admit that I haven't looked at your project very closely yet because I've trouble installing it on my system which is using PipeWire instead of pulseaudio.

**Comment by bugsounet** [comment]
I have +/- patched it for bookworm  using but i admit i'm again under bullseye in my pi (not again to take time to upgrade it)
just tested with my test SDD and works

but works on my dev platform with pipewire and pulseaudio (kubuntu 23.10)

**Comment by KristjanESPERANTO** [comment]
I've got it run by deactivating `sudo raspi-config nonint do_audioconf 1` in the postinstall.sh. raspi-config doesn't exists on my system. Voice Control doesn't work, but for exploring your module its enough. You did I very good job! :+1: 

Setting up the API is a bit annoying, but there's certainly nothing you can do about it.

**Comment by bugsounet** [comment]
> I've got it run by deactivating sudo raspi-config nonint do_audioconf 1 in the postinstall.sh. raspi-config doesn't exists on my system. Voice Control doesn't work, but for exploring your module its enough. You did I very good job! 👍

Sure, it's complex to manage between each OS
That why I make choice to create installer for offical Raspbian and my own OS
It's the result of ~4 years of coding
In all case Thx ;)

> Setting up the API is a bit annoying, but there's certainly nothing you can do about it.

Yes... and I can't do better :/


Notes: 
 * You understand now why I create my own forum and have some dedicated server
 * It's better for manage

**Comment by bugsounet** [comment]
@KristjanESPERANTO 

One small question: your 3rd Party Modules List have self update timer ? Or you have to do it manually ?

**Comment by KristjanESPERANTO** [comment]
> One small question: your 3rd Party Modules List have self update timer ? Or you have to do it manually ?

It is still a manual process. I currently do it several times a week, but I'm also working on automating it. I'm confident that I'll be implementing this soon.

**Pull request merged**
